### ISSUE TITLE
Streamable compression interface

### ISSUE THREAD

**Issue by jimhester** [sbearrows/zstd#2]
I think an interface that reads from an input R connection and writes to an output R connection would make sense.

https://facebook.github.io/zstd/zstd_manual.html#Chapter8 has the docs for the streaming interface, but there is an [example program](https://github.com/facebook/zstd/blob/2ee2cf9cdf7c70d6b3041e0fd0c154989d8d3e19/examples/streaming_compression.c#L28-L86) in the repo that might be easier to adapt to our use case.

https://github.com/tidyverse/readr/blob/master/src/connection.h#L1-L27 has code you can use to read and write to a R connection.

You will also need to close the connection by calling `base::close()` from C++ with something like

```r
static auto close = cpp11::package("base")["close"];
close(in_con)
```

**Comment by sbearrows** [comment]
Nice! Thanks for the links. I'll start implementing this soon.

**Comment by jimhester** [comment]
```r
in_con <- file("my-file", "rb")
out_con <- file("foo", "wb")
x <- my_streaming_compression_function(in_con, out_con, 10)
```

**Comment by jimhester** [comment]
One thing we could also add is support for multiple worker threads when compressing.

This looks like the property you need to set https://github.com/facebook/zstd/blob/18d02cbf2e0654de08093094f1a77cfd231f11d7/examples/streaming_compression.c#L42

On the R side we could query `parallel::detectCores()` to dynamically pick the maximum number of workers for the machine.

**Comment by sbearrows** [comment]
So I can set the ZSTD_c_nbWorkers parameter to the number of CPU cores using detectCores() like this?

```
static auto detectCores = cpp11::package("parallel")["detectCores"];
ZSTD_CCtx_setParameter(cctx, ZSTD_c_nbWorkers, detectCores());
```

**Comment by jimhester** [comment]
I was thinking it would be an extra parameter users would pass from R with that as the default.

However cpp11 doesn't currently support default arguments, so you would need to write an R wrapper around the current function.

**Comment by sbearrows** [comment]
Gotcha! So I should add a new R file in the R folder to write the R wrapper with code like this and edit the stream compression function accordingly?

```
stream_compression <- function(src, dest, level, cores = parallel::detectCores()) {
   stream_compression(src, dest, level, cores)
}
```

**Comment by jimhester** [comment]
yeah, exactly, as a convention we often add a trailing underscore for internal C++ function names, so it would be something like this. (with the name also changed in `code.cpp`)
```r
stream_compression <- function(src, dest, level, cores = parallel::detectCores()) {
   stream_compression_(src, dest, level, cores)
}
```
