### ISSUE TITLE
Alternative function names?

### ISSUE THREAD

**Issue by jimhester** [sbearrows/zstd#5]
The current names are

- compression
- decompression
- stream_compression
- stream_decompression

A good rule of thumb is functions names are verbs, it makes it easier to read the code out loud.

In addition it is often helpful to name the functions after their inputs, which would suggest naming them something like this.

- compress_raw
- decompress_raw
- compress_connection
- decompress_connection

Or _possibly_ naming them similar to how you would use `zstd` and `unzstd` on the command line, though this sort of breaks the verb advice above.

- zstd_raw
- unzstd_raw
- zstd_connection
- unzstd_connection

It might also be a nice convenience to provide a `compress_file` and `decompress_file` functions, which creates the `file()` connections and calls `compress_connection` under the hood.

**Comment by sbearrows** [comment]
Would you still make compress_connection and decompress_connection public/available?

**Comment by jimhester** [comment]
Yes, though if check if `src` and `dst` is already a connection we wouldn't have to, e.g.

```r
compress_file <- function(src, dst, level, threads) {
  if (!inherits(src, "connection")) {
    src <- file(src)
  }
  if (!inherits(dst, "connection")) {
    dst <- file(dst)
  }
  compress_connection_(src, dst, level, threads)
}
```

That seems like a pretty nice interface.

**Comment by sbearrows** [comment]
Oh yeah that looks great!
