### ISSUE TITLE
Documentation not quite correct

### ISSUE THREAD

**Issue by jimhester** [sbearrows/zstd#6]
https://github.com/sbearrows/zstd/blob/c2ac9a740c7b1e137d8a4c5d8f9dd04973b68cd4/R/zstd.R#L5-L7

For the current `compression` and `decompression` functions the input and outputs are raw vectors, not file paths.

For the current `streaming_compression` and `stremaing_decompression` the inputs and outputs are R connections.

So either we would need to use different names for the arguments, or document the groups of functions in separate documentation files.

**Comment by jimhester** [comment]
Also it looks like the standard extension for Zstandard files is `.zst`, from looking at `man zstd`

> When compressing, the suffix .zst is appended to the source filename to get the target filename.

**Comment by sbearrows** [comment]
Mmhm, I think I'll change the variable names. Thanks for catching this!
